### ISSUE TITLE
Closed_at field seems to be missing

### ISSUE THREAD

**Issue by Casper-Yoast** [singer-io/tap-helpscout#20]
I was looking into the tables we replicate from Helpscout, especially the conversations table. 
It seems that there is a created_at field, but no closed_at field, is that right? 
that field would be very usefull for us to gain insight in ticket workflow. 

Thanks in advance!

**Comment by kethan1122** [comment]
Hello @Casper-Yoast . `closed_at` field has been added to `conversations` stream in `v1.1.1`
