### ISSUE TITLE
New tables by Helpscout

### ISSUE THREAD

**Issue by mayank-da** [singer-io/tap-helpscout#29]
I was looking at the API from Helpscout and realized there have been some new tables that are not included in this integration. 
Ratings,
Reports, and
Teams.

This would be great to have to get insights into customer satisfaction and team performance.

Thanks a lot in advance.

**Comment by PeerRich** [comment]
I am looking for ratings, too! https://developer.helpscout.com/mailbox-api/endpoints/ratings/get/

**Comment by PeerRich** [comment]
would love to pay someone to do this

**Comment by kethan1122** [comment]
@PeerRich @mayank-da Is it possible to get all the ratingIds?

- In the API request, it was expecting ratingID as [endpoint](https://developer.helpscout.com/mailbox-api/endpoints/ratings/get/#path-parameters). Without knowing ratingId, it is not possible to use that endpoint
- I see ratings are given for a conversation or for a conversation thread, Is it possible to get the ratings using either conversationId or threadID. I've gone their endpoints documentation but couldn't find anything

Please correct me, if I missed something

**Comment by kethan1122** [comment]
new streams were released in v1.2.0
