### ISSUE TITLE
Custom fields on Customers endpoint

### ISSUE THREAD

**Issue by arthur-borcato** [singer-io/tap-helpscout#31]
Hello there,

I noticed that the current schema does not return the customers custom fields created on Helpscout. It's returned inside "properties" array in "_embedded" as it's possible to check on the documentation (https://developer.helpscout.com/mailbox-api/endpoints/customers/list/). It would be really nice for me to have this property on Stitch. If you guys doesn't have time to do that but can give me a little explanation I can do it and open a PR.

Thank you in advance!

**Comment by kethan1122** [comment]
Closing this issue.
Issue has been addressed in this [PR](https://github.com/singer-io/tap-helpscout/pull/32)
