### ISSUE TITLE
Data for a few months is missing

### ISSUE THREAD

**Issue by harall10** [singer-io/tap-helpscout#4]
Hi, I noticed that we have all data missing from Nov 2018 to Feb 2019. Data before this and after seems to be available.

**Comment by harall10** [comment]
Follow up - seems like "conversations" are available for those time periods, but not "conversation threads".

**Comment by pjatx** [comment]
@harall10 I'm also noticing missing conversation threads data. Were you able to resolve?

**Comment by harall10** [comment]
@pjatx Yes, I was able to resolve through the Singer Slack community: https://singer-slackin.herokuapp.com/. You can post the issue in here.
